import { Button } from "@/components/ui/button";
import { Download, Eye, Lock } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useState } from "react";
import { PdfPreviewModal } from "@/components/PdfPreviewModal";
import { generatePdfContent, downloadPdf, type NoteContent } from "@/utils/pdfGenerator";

const Library = () => {
  const { toast } = useToast();
  const [showPreview, setShowPreview] = useState(false);
  const [selectedNote, setSelectedNote] = useState<NoteContent | null>(null);

  const sampleNotes = [
    {
      title: "Data Structures and Algorithms",
      subject: "Computer Science",
      semester: "Semester 3",
      topics: ["Arrays", "Linked Lists", "Trees", "Graphs", "Sorting Algorithms"],
      pages: 45,
      downloads: 2345,
      isPremium: false,
    },
    {
      title: "Organic Chemistry Fundamentals",
      subject: "Chemistry",
      semester: "Semester 2",
      topics: ["Hydrocarbons", "Functional Groups", "Reactions", "Mechanisms"],
      pages: 38,
      downloads: 1876,
      isPremium: false,
    },
    {
      title: "Financial Accounting Principles",
      subject: "Business",
      semester: "Semester 1",
      topics: ["Balance Sheet", "Income Statement", "Cash Flow", "Ratios"],
      pages: 52,
      downloads: 3021,
      isPremium: true,
    },
    {
      title: "Human Anatomy & Physiology",
      subject: "Medical Science",
      semester: "Semester 1",
      topics: ["Cardiovascular", "Respiratory", "Nervous System", "Muscular"],
      pages: 67,
      downloads: 4102,
      isPremium: true,
    },
    {
      title: "Environmental Science",
      subject: "Science",
      semester: "Semester 4",
      topics: ["Ecosystems", "Pollution", "Biodiversity", "Climate Change"],
      pages: 41,
      downloads: 1543,
      isPremium: false,
    },
    {
      title: "Digital Marketing Strategies",
      subject: "Marketing",
      semester: "Semester 5",
      topics: ["SEO", "Social Media", "Content Marketing", "Analytics"],
      pages: 36,
      downloads: 2187,
      isPremium: true,
    },
  ];

  const handlePreview = (note: typeof sampleNotes[0]) => {
    if (note.isPremium) {
      toast({
        title: "Premium Content",
        description: "Upgrade to premium to access this sample note.",
        variant: "destructive",
      });
    } else {
      const noteContent: NoteContent = {
        title: note.title,
        subject: note.subject,
        topics: note.topics,
        isPremium: note.isPremium,
      };
      setSelectedNote(noteContent);
      setShowPreview(true);
    }
  };

  const handleDownload = (note: typeof sampleNotes[0]) => {
    if (note.isPremium) {
      toast({
        title: "Premium Content",
        description: "Upgrade to premium to access this sample note.",
        variant: "destructive",
      });
    } else {
      const noteContent: NoteContent = {
        title: note.title,
        subject: note.subject,
        topics: note.topics,
        isPremium: note.isPremium,
      };
      downloadPdf(noteContent);
      toast({
        title: "Download started!",
        description: `${note.title} is being downloaded.`,
      });
    }
  };

  const handleDownloadFromPreview = () => {
    if (selectedNote) {
      downloadPdf(selectedNote);
      toast({
        title: "Download started!",
        description: "Your PDF is being downloaded.",
      });
    }
  };

  return (
    <div className="min-h-screen">
      {selectedNote && (
        <PdfPreviewModal
          open={showPreview}
          onClose={() => setShowPreview(false)}
          pdfContent={generatePdfContent(selectedNote)}
          title={selectedNote.title}
          onDownload={handleDownloadFromPreview}
        />
      )}
      {/* Hero */}
      <section className="bg-gradient-to-br from-background via-primary/5 to-secondary/5 py-20">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">Notes Library</h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Browse sample notes generated by SyllabusToNotes across various subjects and courses. See the quality
            before you generate your own!
          </p>
        </div>
      </section>

      {/* Sample Notes Grid */}
      <section className="py-20">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center mb-8">
            <h2 className="text-2xl font-bold">Sample Study Notes</h2>
            <p className="text-sm text-muted-foreground">
              {sampleNotes.length} samples available
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {sampleNotes.map((note, index) => (
              <div
                key={index}
                className="bg-card rounded-lg p-6 shadow-[var(--shadow-card)] hover:shadow-lg transition-all border border-border relative overflow-hidden"
              >
                {note.isPremium && (
                  <div className="absolute top-0 right-0 bg-secondary text-secondary-foreground px-3 py-1 text-xs font-bold rounded-bl-lg">
                    PREMIUM
                  </div>
                )}
                
                <div className="mb-4">
                  <h3 className="text-xl font-bold mb-2 line-clamp-2">{note.title}</h3>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground mb-3">
                    <span className="bg-primary/10 text-primary px-2 py-1 rounded">{note.subject}</span>
                    <span>{note.semester}</span>
                  </div>
                </div>

                <div className="mb-4">
                  <p className="text-sm text-muted-foreground mb-2">Topics Covered:</p>
                  <div className="flex flex-wrap gap-1">
                    {note.topics.slice(0, 3).map((topic, i) => (
                      <span key={i} className="text-xs bg-muted px-2 py-1 rounded">
                        {topic}
                      </span>
                    ))}
                    {note.topics.length > 3 && (
                      <span className="text-xs bg-muted px-2 py-1 rounded">
                        +{note.topics.length - 3} more
                      </span>
                    )}
                  </div>
                </div>

                <div className="flex items-center justify-between text-sm text-muted-foreground mb-4">
                  <span>{note.pages} pages</span>
                  <span className="flex items-center gap-1">
                    <Download className="h-4 w-4" />
                    {note.downloads} downloads
                  </span>
                </div>

                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    className="flex-1"
                    onClick={() => handlePreview(note)}
                  >
                    {note.isPremium ? (
                      <>
                        <Lock className="h-4 w-4 mr-1" />
                        Preview
                      </>
                    ) : (
                      <>
                        <Eye className="h-4 w-4 mr-1" />
                        View
                      </>
                    )}
                  </Button>
                  <Button
                    variant={note.isPremium ? "secondary" : "default"}
                    size="sm"
                    className="flex-1"
                    onClick={() => handleDownload(note)}
                  >
                    <Download className="h-4 w-4 mr-1" />
                    Download
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Quality Showcase */}
      <section className="py-20 bg-card">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold mb-8 text-center">What's Inside Our Notes?</h2>
            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-background rounded-lg p-6 border border-border">
                <h3 className="text-xl font-bold mb-3">Free Notes Include:</h3>
                <ul className="space-y-2 text-muted-foreground">
                  <li className="flex items-start">
                    <span className="text-primary mr-2">✓</span>
                    <span>Complete topic summaries from syllabus</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-primary mr-2">✓</span>
                    <span>Key concepts and definitions</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-primary mr-2">✓</span>
                    <span>Organized structure with headings</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-primary mr-2">✓</span>
                    <span>Clean PDF formatting for easy reading</span>
                  </li>
                </ul>
              </div>

              <div className="bg-gradient-to-br from-secondary/10 to-accent/10 rounded-lg p-6 border border-secondary/20">
                <h3 className="text-xl font-bold mb-3">Premium Notes Add:</h3>
                <ul className="space-y-2 text-muted-foreground">
                  <li className="flex items-start">
                    <span className="text-secondary mr-2">✓</span>
                    <span>Detailed explanations and examples</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-secondary mr-2">✓</span>
                    <span>Visual diagrams and flowcharts</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-secondary mr-2">✓</span>
                    <span>Previous year exam questions</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-secondary mr-2">✓</span>
                    <span>Custom templates and styling options</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 bg-gradient-to-br from-primary/10 to-secondary/10">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl font-bold mb-6">Ready to Generate Your Own Notes?</h2>
          <p className="text-lg text-muted-foreground mb-8 max-w-2xl mx-auto">
            Upload your syllabus and get AI-generated study notes in seconds, just like these samples
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button variant="hero" size="lg" asChild>
              <a href="/#upload">Generate Notes Now</a>
            </Button>
            <Button variant="outline" size="lg" asChild>
              <a href="/premium">View Premium Plans</a>
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Library;
