import jsPDF from 'jspdf';

export interface Chapter {
  name: string;
  description: string;
  keyPoints: string[];
  applications: string;
}

export interface Module {
  name: string;
  chapters: Chapter[];
}

export interface NoteContent {
  title: string;
  subject: string;
  topics?: string[];
  modules?: Module[];
  isPremium?: boolean;
}

export const generatePdfContent = (content: NoteContent): string => {
  const { title, subject, topics, modules } = content;
  
  // Generate content based on whether we have AI-analyzed modules or simple topics
  const mainContent = modules ? generateModuleContent(modules) : generateTopicContent(topics || []);
  
  return `
    <div style="font-family: Arial, sans-serif; line-height: 1.6;">
      <h1 style="color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px;">
        ${title}
      </h1>
      <p style="color: #666; margin: 10px 0;">
        <strong>Subject:</strong> ${subject}
      </p>
      
      ${mainContent}
      
      <div style="margin-top: 40px; padding: 20px; background: #eff6ff; border-radius: 8px; border: 1px solid #2563eb;">
        <h3 style="color: #2563eb; margin-top: 0;">Study Tips:</h3>
        <ul style="color: #1e40af;">
          <li>Review these notes regularly for better retention</li>
          <li>Create your own examples for each concept</li>
          <li>Practice with previous year questions</li>
          <li>Form study groups to discuss topics</li>
        </ul>
      </div>
      
      <div style="margin-top: 20px; padding: 15px; background: #f9fafb; border-radius: 8px; text-align: center; color: #6b7280;">
        <p style="margin: 0;">Generated by <strong style="color: #2563eb;">SyllabusToNotes</strong></p>
        <p style="margin: 5px 0 0 0; font-size: 12px;">AI-Powered Study Notes</p>
      </div>
    </div>
  `;
};

const getTopicDescription = (topic: string): string => {
  const descriptions: { [key: string]: string } = {
    'Arrays': 'A data structure that stores a collection of elements, each identified by an array index. Arrays provide efficient random access and are fundamental to many algorithms.',
    'Linked Lists': 'A linear data structure where elements are stored in nodes, with each node containing a reference to the next node. Useful for dynamic memory allocation.',
    'Trees': 'A hierarchical data structure with a root node and child nodes, forming a parent-child relationship. Used in file systems, databases, and more.',
    'Graphs': 'A collection of nodes connected by edges, used to represent networks, relationships, and pathways in various applications.',
    'Sorting Algorithms': 'Algorithms that arrange elements in a specific order (ascending/descending). Common examples include bubble sort, merge sort, and quick sort.',
    'Hydrocarbons': 'Organic compounds consisting entirely of hydrogen and carbon atoms. They form the basis of organic chemistry.',
    'Functional Groups': 'Specific groups of atoms within molecules that are responsible for characteristic chemical reactions.',
    'Reactions': 'Chemical processes where substances are transformed into different substances through breaking and forming chemical bonds.',
    'Mechanisms': 'Step-by-step descriptions of how chemical reactions occur at the molecular level.',
    'Balance Sheet': 'A financial statement that reports company assets, liabilities, and shareholders equity at a specific point in time.',
    'Income Statement': 'A financial statement showing revenues and expenses during a specific period, resulting in net profit or loss.',
    'Cash Flow': 'The total amount of money being transferred in and out of a business, affecting liquidity.',
    'Ratios': 'Financial metrics used to evaluate various aspects of company performance and financial health.',
    'Cardiovascular': 'The system comprising the heart and blood vessels responsible for circulating blood throughout the body.',
    'Respiratory': 'The biological system for gas exchange, bringing oxygen into the body and removing carbon dioxide.',
    'Nervous System': 'The network of nerve cells and fibers that transmits signals between different parts of the body.',
    'Muscular': 'The system of muscles that enables movement and maintains posture in the body.',
    'Ecosystems': 'A community of living organisms interacting with their physical environment.',
    'Pollution': 'The introduction of harmful substances or contaminants into the natural environment.',
    'Biodiversity': 'The variety of life in all its forms, levels, and combinations, including diversity of species.',
    'Climate Change': 'Long-term shifts in temperatures and weather patterns, primarily caused by human activities.',
    'SEO': 'Search Engine Optimization - techniques to improve website visibility in search engine results.',
    'Social Media': 'Digital platforms enabling users to create and share content, facilitating online social networking.',
    'Content Marketing': 'Strategic marketing approach focused on creating valuable content to attract and retain audiences.',
    'Analytics': 'The systematic analysis of data to gain insights and make informed decisions.',
  };
  
  return descriptions[topic] || `Comprehensive coverage of ${topic} including fundamental concepts, practical applications, and key theoretical foundations.`;
};

const generateModuleContent = (modules: Module[]): string => {
  return `
    <h2 style="color: #7c3aed; margin-top: 30px;">Course Content:</h2>
    ${modules.map((module, moduleIndex) => `
      <div style="margin: 30px 0;">
        <h2 style="color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 8px;">
          Module ${moduleIndex + 1}: ${module.name}
        </h2>
        ${module.chapters.map((chapter, chapterIndex) => `
          <div style="background: #f3f4f6; margin: 15px 0; padding: 20px; border-left: 4px solid #2563eb; border-radius: 4px;">
            <h3 style="color: #1f2937; margin: 0 0 15px 0;">
              ${moduleIndex + 1}.${chapterIndex + 1} ${chapter.name}
            </h3>
            <p style="color: #4b5563; margin: 0 0 15px 0; line-height: 1.8;">
              ${chapter.description}
            </p>
            
            <div style="background: white; padding: 15px; border-radius: 4px; margin: 15px 0;">
              <strong style="color: #2563eb; font-size: 16px;">📌 Key Points:</strong>
              <ul style="margin: 10px 0; padding-left: 25px; color: #374151;">
                ${chapter.keyPoints.map(point => `<li style="margin: 5px 0;">${point}</li>`).join('')}
              </ul>
            </div>
            
            <div style="background: #eff6ff; padding: 15px; border-radius: 4px; border-left: 3px solid #3b82f6;">
              <strong style="color: #1e40af; font-size: 15px;">💡 Practical Applications:</strong>
              <p style="color: #1e3a8a; margin: 8px 0 0 0; line-height: 1.7;">
                ${chapter.applications}
              </p>
            </div>
          </div>
        `).join('')}
      </div>
    `).join('')}
  `;
};

const generateTopicContent = (topics: string[]): string => {
  return `
    <h2 style="color: #7c3aed; margin-top: 30px;">Topics Covered:</h2>
    <ul style="list-style-type: none; padding-left: 0;">
      ${topics.map(topic => `
        <li style="background: #f3f4f6; margin: 10px 0; padding: 15px; border-left: 4px solid #2563eb; border-radius: 4px;">
          <h3 style="color: #1f2937; margin: 0 0 10px 0;">${topic}</h3>
          <p style="color: #4b5563; margin: 0;">
            ${getTopicDescription(topic)}
          </p>
          <div style="margin-top: 10px; padding: 10px; background: white; border-radius: 4px;">
            <strong style="color: #2563eb;">Key Points:</strong>
            <ul style="margin: 5px 0; padding-left: 20px;">
              ${getKeyPoints(topic).map(point => `<li style="color: #374151;">${point}</li>`).join('')}
            </ul>
          </div>
        </li>
      `).join('')}
    </ul>
  `;
};

const getKeyPoints = (topic: string): string[] => {
  const keyPoints: { [key: string]: string[] } = {
    'Arrays': [
      'Fixed size, contiguous memory allocation',
      'O(1) access time using index',
      'Common operations: insert, delete, search, traverse',
      'Types: 1D, 2D, multi-dimensional arrays'
    ],
    'Linked Lists': [
      'Dynamic size, non-contiguous memory',
      'Types: Singly, Doubly, Circular',
      'Efficient insertion and deletion',
      'Sequential access O(n)'
    ],
    'Trees': [
      'Root, parent, child, leaf nodes',
      'Binary trees, BST, AVL, B-trees',
      'Traversal: Inorder, Preorder, Postorder',
      'Applications: file systems, decision trees'
    ],
    'Graphs': [
      'Vertices (nodes) and Edges',
      'Directed vs Undirected graphs',
      'Weighted vs Unweighted',
      'Traversal: BFS, DFS'
    ],
  };
  
  return keyPoints[topic] || [
    'Core concepts and definitions',
    'Practical applications and examples',
    'Common problems and solutions',
    'Best practices and techniques'
  ];
};

export const downloadPdf = (content: NoteContent) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = 20;
  
  // Title
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235);
  doc.text(content.title, margin, yPosition);
  yPosition += 10;
  
  // Line under title
  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(1);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 15;
  
  // Subject
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Subject: ${content.subject}`, margin, yPosition);
  yPosition += 15;
  
  // Generate content based on structure
  if (content.modules) {
    // AI-analyzed content with modules
    content.modules.forEach((module, moduleIndex) => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }
      
      // Module heading
      doc.setFontSize(16);
      doc.setTextColor(37, 99, 235);
      doc.text(`Module ${moduleIndex + 1}: ${module.name}`, margin, yPosition);
      yPosition += 10;
      
      module.chapters.forEach((chapter, chapterIndex) => {
        if (yPosition > 260) {
          doc.addPage();
          yPosition = 20;
        }
        
        // Chapter heading
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.setFont(undefined, 'bold');
        doc.text(`${moduleIndex + 1}.${chapterIndex + 1} ${chapter.name}`, margin + 5, yPosition);
        yPosition += 8;
        
        // Description
        doc.setFontSize(11);
        doc.setFont(undefined, 'normal');
        const splitDesc = doc.splitTextToSize(chapter.description, pageWidth - 2 * margin - 10);
        doc.text(splitDesc, margin + 5, yPosition);
        yPosition += splitDesc.length * 5 + 8;
        
        // Key Points
        if (yPosition > 250) {
          doc.addPage();
          yPosition = 20;
        }
        doc.setFont(undefined, 'bold');
        doc.text('Key Points:', margin + 5, yPosition);
        yPosition += 6;
        
        doc.setFont(undefined, 'normal');
        chapter.keyPoints.forEach(point => {
          if (yPosition > 270) {
            doc.addPage();
            yPosition = 20;
          }
          const splitPoint = doc.splitTextToSize(`• ${point}`, pageWidth - 2 * margin - 15);
          doc.text(splitPoint, margin + 10, yPosition);
          yPosition += splitPoint.length * 5 + 2;
        });
        
        yPosition += 5;
        
        // Applications
        if (yPosition > 250) {
          doc.addPage();
          yPosition = 20;
        }
        doc.setFont(undefined, 'bold');
        doc.text('Practical Applications:', margin + 5, yPosition);
        yPosition += 6;
        
        doc.setFont(undefined, 'normal');
        const splitApp = doc.splitTextToSize(chapter.applications, pageWidth - 2 * margin - 10);
        doc.text(splitApp, margin + 5, yPosition);
        yPosition += splitApp.length * 5 + 12;
      });
      
      yPosition += 5;
    });
  } else if (content.topics) {
    // Simple topic-based content
    doc.setFontSize(16);
    doc.setTextColor(124, 58, 237);
    doc.text('Topics Covered:', margin, yPosition);
    yPosition += 10;
    
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    content.topics.forEach((topic, index) => {
      if (yPosition > 270) {
        doc.addPage();
        yPosition = 20;
      }
      
      doc.setFont(undefined, 'bold');
      doc.text(`${index + 1}. ${topic}`, margin, yPosition);
      yPosition += 7;
      
      doc.setFont(undefined, 'normal');
      const description = getTopicDescription(topic);
      const splitDescription = doc.splitTextToSize(description, pageWidth - 2 * margin);
      doc.text(splitDescription, margin + 5, yPosition);
      yPosition += splitDescription.length * 5 + 5;
      
      const keyPoints = getKeyPoints(topic);
      doc.setFont(undefined, 'bold');
      doc.text('Key Points:', margin + 5, yPosition);
      yPosition += 6;
      
      doc.setFont(undefined, 'normal');
      keyPoints.forEach(point => {
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }
        const splitPoint = doc.splitTextToSize(`• ${point}`, pageWidth - 2 * margin - 10);
        doc.text(splitPoint, margin + 10, yPosition);
        yPosition += splitPoint.length * 5 + 2;
      });
      
      yPosition += 10;
    });
  }
  
  // Footer
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }
  
  doc.setFillColor(239, 246, 255);
  doc.rect(margin, yPosition, pageWidth - 2 * margin, 30, 'F');
  doc.setFontSize(10);
  doc.setTextColor(37, 99, 235);
  doc.text('Generated by SyllabusToNotes', pageWidth / 2, yPosition + 15, { align: 'center' });
  doc.text('AI-Powered Study Notes', pageWidth / 2, yPosition + 22, { align: 'center' });
  
  // Save
  doc.save(`${content.title.replace(/[^a-z0-9]/gi, '_')}.pdf`);
};
