import jsPDF from 'jspdf';

export interface Chapter {
  name: string;
  description: string;
  definition?: string;
  keyPoints: string[];
  applications: string;
  formulas?: string[];
  tables?: Array<{ title: string; headers: string[]; rows: string[][] }>;
  importantConcepts?: string[];
  commonMistakes?: string[];
  studyTips?: string[];
  previousYearQuestions?: string[];
  relatedTopics?: string[];
  isImportant?: boolean;
}

export interface Module {
  name: string;
  description?: string;
  chapters: Chapter[];
}

export interface NoteContent {
  title: string;
  subject: string;
  courseCode?: string;
  topics?: string[];
  modules?: Module[];
  isPremium?: boolean;
}

export const generatePdfContent = (content: NoteContent): string => {
  const { title, subject, courseCode, topics, modules } = content;
  
  // Generate content based on whether we have AI-analyzed modules or simple topics
  const mainContent = modules ? generateModuleContent(modules) : generateTopicContent(topics || []);
  
  return `
    <div style="font-family: Arial, sans-serif; line-height: 1.8;">
      <!-- Header -->
      <div style="background: linear-gradient(135deg, #2563eb 0%, #1e40af 100%); 
                  color: white; padding: 30px; border-radius: 12px; margin-bottom: 30px;">
        <h1 style="margin: 0 0 10px 0; font-size: 32px; border-bottom: 3px solid white; padding-bottom: 15px;">
          ${subject}
        </h1>
        <div style="display: flex; gap: 20px; margin-top: 15px; font-size: 14px;">
          <p style="margin: 0;"><strong>Subject:</strong> ${subject}</p>
          ${courseCode ? `<p style="margin: 0;"><strong>Course Code:</strong> ${courseCode}</p>` : ''}
        </div>
      </div>
      
      ${mainContent}
      
      <!-- Study Tips Section -->
      <div style="margin-top: 50px; padding: 25px; background: linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%); 
                  border-radius: 12px; border-left: 5px solid #2563eb;">
        <h3 style="color: #2563eb; margin-top: 0; font-size: 20px; display: flex; align-items: center;">
          💡 Essential Study Tips
        </h3>
        <ul style="color: #1e40af; margin: 15px 0; line-height: 2;">
          <li><strong>Regular Review:</strong> Review these notes daily for better retention and understanding</li>
          <li><strong>Active Learning:</strong> Create your own examples and practice problems for each concept</li>
          <li><strong>Practice:</strong> Solve previous year questions and sample papers regularly</li>
          <li><strong>Study Groups:</strong> Form study groups to discuss and clarify difficult topics</li>
          <li><strong>Time Management:</strong> Allocate more time to topics marked as important</li>
          <li><strong>Connections:</strong> Try to connect different topics to build a comprehensive understanding</li>
        </ul>
      </div>
      
      <!-- Footer -->
      <div style="margin-top: 30px; padding: 20px; background: #f9fafb; border-radius: 8px; 
                  text-align: center; color: #6b7280; border-top: 3px solid #2563eb;">
        <p style="margin: 0; font-size: 16px;">
          Generated by <strong style="color: #2563eb; font-size: 18px;">SyllabusToNotes.com</strong>
        </p>
        <p style="margin: 8px 0 0 0; font-size: 13px; color: #9ca3af;">
          AI-Powered Comprehensive Study Notes | Visit us at www.syllabustonotes.com
        </p>
      </div>
    </div>
  `;
};

const getTopicDescription = (topic: string): string => {
  const descriptions: { [key: string]: string } = {
    'Arrays': 'A data structure that stores a collection of elements, each identified by an array index. Arrays provide efficient random access and are fundamental to many algorithms.',
    'Linked Lists': 'A linear data structure where elements are stored in nodes, with each node containing a reference to the next node. Useful for dynamic memory allocation.',
    'Trees': 'A hierarchical data structure with a root node and child nodes, forming a parent-child relationship. Used in file systems, databases, and more.',
    'Graphs': 'A collection of nodes connected by edges, used to represent networks, relationships, and pathways in various applications.',
    'Sorting Algorithms': 'Algorithms that arrange elements in a specific order (ascending/descending). Common examples include bubble sort, merge sort, and quick sort.',
    'Hydrocarbons': 'Organic compounds consisting entirely of hydrogen and carbon atoms. They form the basis of organic chemistry.',
    'Functional Groups': 'Specific groups of atoms within molecules that are responsible for characteristic chemical reactions.',
    'Reactions': 'Chemical processes where substances are transformed into different substances through breaking and forming chemical bonds.',
    'Mechanisms': 'Step-by-step descriptions of how chemical reactions occur at the molecular level.',
    'Balance Sheet': 'A financial statement that reports company assets, liabilities, and shareholders equity at a specific point in time.',
    'Income Statement': 'A financial statement showing revenues and expenses during a specific period, resulting in net profit or loss.',
    'Cash Flow': 'The total amount of money being transferred in and out of a business, affecting liquidity.',
    'Ratios': 'Financial metrics used to evaluate various aspects of company performance and financial health.',
    'Cardiovascular': 'The system comprising the heart and blood vessels responsible for circulating blood throughout the body.',
    'Respiratory': 'The biological system for gas exchange, bringing oxygen into the body and removing carbon dioxide.',
    'Nervous System': 'The network of nerve cells and fibers that transmits signals between different parts of the body.',
    'Muscular': 'The system of muscles that enables movement and maintains posture in the body.',
    'Ecosystems': 'A community of living organisms interacting with their physical environment.',
    'Pollution': 'The introduction of harmful substances or contaminants into the natural environment.',
    'Biodiversity': 'The variety of life in all its forms, levels, and combinations, including diversity of species.',
    'Climate Change': 'Long-term shifts in temperatures and weather patterns, primarily caused by human activities.',
    'SEO': 'Search Engine Optimization - techniques to improve website visibility in search engine results.',
    'Social Media': 'Digital platforms enabling users to create and share content, facilitating online social networking.',
    'Content Marketing': 'Strategic marketing approach focused on creating valuable content to attract and retain audiences.',
    'Analytics': 'The systematic analysis of data to gain insights and make informed decisions.',
  };
  
  return descriptions[topic] || `Comprehensive coverage of ${topic} including fundamental concepts, practical applications, and key theoretical foundations.`;
};

const generateModuleContent = (modules: Module[]): string => {
  return `
    <h2 style="color: #7c3aed; margin-top: 30px; font-size: 24px; border-bottom: 3px solid #7c3aed; padding-bottom: 10px;">
      📚 Course Content
    </h2>
    ${modules.map((module, moduleIndex) => `
      <div style="margin: 40px 0; page-break-inside: avoid;">
        <div style="background: linear-gradient(135deg, #7c3aed 0%, #6d28d9 100%); 
                    color: white; padding: 20px; border-radius: 10px; margin-bottom: 20px;">
          <h2 style="margin: 0; font-size: 22px;">
            Module ${moduleIndex + 1}: ${module.name}
          </h2>
          ${module.description ? `<p style="margin: 10px 0 0 0; opacity: 0.95; font-size: 14px;">${module.description}</p>` : ''}
        </div>
        
        ${module.chapters.map((chapter, chapterIndex) => `
          <div style="background: ${chapter.isImportant ? '#fef3c7' : '#f3f4f6'}; 
                      margin: 20px 0; padding: 25px; 
                      border-left: 5px solid ${chapter.isImportant ? '#f59e0b' : '#2563eb'}; 
                      border-radius: 8px; page-break-inside: avoid;">
            
            <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 15px;">
              <h3 style="color: #1f2937; margin: 0; font-size: 20px;">
                ${moduleIndex + 1}.${chapterIndex + 1} ${chapter.name}
              </h3>
              ${chapter.isImportant ? '<span style="background: #f59e0b; color: white; padding: 4px 12px; border-radius: 12px; font-size: 11px; font-weight: bold;">⭐ IMPORTANT</span>' : ''}
            </div>
            
            ${chapter.definition ? `
              <div style="background: white; padding: 15px; border-radius: 6px; margin: 15px 0; border-left: 3px solid #8b5cf6;">
                <strong style="color: #8b5cf6; font-size: 15px;">📖 Definition:</strong>
                <p style="color: #374151; margin: 8px 0 0 0; line-height: 1.8; font-style: italic;">
                  ${chapter.definition}
                </p>
              </div>
            ` : ''}
            
            <div style="background: white; padding: 15px; border-radius: 6px; margin: 15px 0;">
              <strong style="color: #4b5563; font-size: 15px;">📝 Overview:</strong>
              <p style="color: #4b5563; margin: 8px 0 0 0; line-height: 1.9;">
                ${chapter.description}
              </p>
            </div>
            
            <div style="background: white; padding: 18px; border-radius: 6px; margin: 15px 0;">
              <strong style="color: #2563eb; font-size: 16px; display: block; margin-bottom: 12px;">
                📌 Key Points to Remember:
              </strong>
              <ul style="margin: 0; padding-left: 25px; color: #374151; line-height: 2;">
                ${chapter.keyPoints.map(point => `
                  <li style="margin: 8px 0; padding-left: 5px;">${point}</li>
                `).join('')}
              </ul>
            </div>
            
            ${chapter.importantConcepts && chapter.importantConcepts.length > 0 ? `
              <div style="background: #fef3c7; padding: 18px; border-radius: 6px; margin: 15px 0; border-left: 3px solid #f59e0b;">
                <strong style="color: #d97706; font-size: 16px; display: block; margin-bottom: 12px;">
                  🎯 Important Concepts:
                </strong>
                <ul style="margin: 0; padding-left: 25px; color: #92400e; line-height: 2;">
                  ${chapter.importantConcepts.map(concept => `
                    <li style="margin: 8px 0;">${concept}</li>
                  `).join('')}
                </ul>
              </div>
            ` : ''}
            
            ${chapter.formulas && chapter.formulas.length > 0 ? `
              <div style="background: #f0f9ff; padding: 18px; border-radius: 6px; margin: 15px 0; border-left: 3px solid #0ea5e9;">
                <strong style="color: #0369a1; font-size: 16px; display: block; margin-bottom: 12px;">
                  🔢 Formulas & Equations:
                </strong>
                <div style="background: white; padding: 15px; border-radius: 4px;">
                  ${chapter.formulas.map(formula => `
                    <div style="margin: 10px 0; padding: 10px; background: #f8fafc; border-radius: 4px; font-family: 'Courier New', monospace; color: #0c4a6e;">
                      ${formula}
                    </div>
                  `).join('')}
                </div>
              </div>
            ` : ''}
            
            ${chapter.tables && chapter.tables.length > 0 ? `
              ${chapter.tables.map(table => `
                <div style="background: white; padding: 18px; border-radius: 6px; margin: 15px 0; border: 2px solid #e5e7eb;">
                  <strong style="color: #374151; font-size: 16px; display: block; margin-bottom: 12px;">
                    📊 ${table.title}
                  </strong>
                  <table style="width: 100%; border-collapse: collapse;">
                    <thead>
                      <tr style="background: #f3f4f6;">
                        ${table.headers.map(h => `<th style="padding: 10px; border: 1px solid #d1d5db; text-align: left; font-weight: bold;">${h}</th>`).join('')}
                      </tr>
                    </thead>
                    <tbody>
                      ${table.rows.map(row => `
                        <tr>
                          ${row.map(cell => `<td style="padding: 10px; border: 1px solid #d1d5db;">${cell}</td>`).join('')}
                        </tr>
                      `).join('')}
                    </tbody>
                  </table>
                </div>
              `).join('')}
            ` : ''}
            
            <div style="background: #eff6ff; padding: 18px; border-radius: 6px; margin: 15px 0; border-left: 3px solid #3b82f6;">
              <strong style="color: #1e40af; font-size: 16px; display: block; margin-bottom: 10px;">
                💡 Practical Applications:
              </strong>
              <p style="color: #1e3a8a; margin: 0; line-height: 1.9;">
                ${chapter.applications}
              </p>
            </div>
            
            ${chapter.studyTips && chapter.studyTips.length > 0 ? `
              <div style="background: #f0fdf4; padding: 18px; border-radius: 6px; margin: 15px 0; border-left: 3px solid #10b981;">
                <strong style="color: #059669; font-size: 16px; display: block; margin-bottom: 12px;">
                  ✅ Study Tips:
                </strong>
                <ul style="margin: 0; padding-left: 25px; color: #065f46; line-height: 2;">
                  ${chapter.studyTips.map(tip => `
                    <li style="margin: 8px 0;">${tip}</li>
                  `).join('')}
                </ul>
              </div>
            ` : ''}
            
            ${chapter.previousYearQuestions && chapter.previousYearQuestions.length > 0 ? `
              <div style="background: #fef3c7; padding: 18px; border-radius: 6px; margin: 15px 0; border-left: 3px solid #f59e0b;">
                <strong style="color: #d97706; font-size: 16px; display: block; margin-bottom: 12px;">
                  📝 Previous Year Questions:
                </strong>
                <ol style="margin: 0; padding-left: 25px; color: #92400e; line-height: 2;">
                  ${chapter.previousYearQuestions.map(q => `
                    <li style="margin: 8px 0;">${q}</li>
                  `).join('')}
                </ol>
              </div>
            ` : ''}
            
            ${chapter.relatedTopics && chapter.relatedTopics.length > 0 ? `
              <div style="background: #faf5ff; padding: 15px; border-radius: 6px; margin: 15px 0; border-left: 3px solid #a855f7;">
                <strong style="color: #7e22ce; font-size: 15px;">
                  🔗 Related Topics:
                </strong>
                <p style="color: #6b21a8; margin: 8px 0 0 0;">
                  ${chapter.relatedTopics.join(' • ')}
                </p>
              </div>
            ` : ''}
            
          </div>
        `).join('')}
      </div>
    `).join('')}
  `;
};

const generateTopicContent = (topics: string[]): string => {
  return `
    <h2 style="color: #7c3aed; margin-top: 30px;">Topics Covered:</h2>
    <ul style="list-style-type: none; padding-left: 0;">
      ${topics.map(topic => `
        <li style="background: #f3f4f6; margin: 10px 0; padding: 15px; border-left: 4px solid #2563eb; border-radius: 4px;">
          <h3 style="color: #1f2937; margin: 0 0 10px 0;">${topic}</h3>
          <p style="color: #4b5563; margin: 0;">
            ${getTopicDescription(topic)}
          </p>
          <div style="margin-top: 10px; padding: 10px; background: white; border-radius: 4px;">
            <strong style="color: #2563eb;">Key Points:</strong>
            <ul style="margin: 5px 0; padding-left: 20px;">
              ${getKeyPoints(topic).map(point => `<li style="color: #374151;">${point}</li>`).join('')}
            </ul>
          </div>
        </li>
      `).join('')}
    </ul>
  `;
};

const getKeyPoints = (topic: string): string[] => {
  const keyPoints: { [key: string]: string[] } = {
    'Arrays': [
      'Fixed size, contiguous memory allocation',
      'O(1) access time using index',
      'Common operations: insert, delete, search, traverse',
      'Types: 1D, 2D, multi-dimensional arrays'
    ],
    'Linked Lists': [
      'Dynamic size, non-contiguous memory',
      'Types: Singly, Doubly, Circular',
      'Efficient insertion and deletion',
      'Sequential access O(n)'
    ],
    'Trees': [
      'Root, parent, child, leaf nodes',
      'Binary trees, BST, AVL, B-trees',
      'Traversal: Inorder, Preorder, Postorder',
      'Applications: file systems, decision trees'
    ],
    'Graphs': [
      'Vertices (nodes) and Edges',
      'Directed vs Undirected graphs',
      'Weighted vs Unweighted',
      'Traversal: BFS, DFS'
    ],
  };
  
  return keyPoints[topic] || [
    'Core concepts and definitions',
    'Practical applications and examples',
    'Common problems and solutions',
    'Best practices and techniques'
  ];
};

// Sanitize text to avoid PDF encoding issues and stray symbols
const sanitizeText = (s: string): string => {
  if (!s) return '';
  try {
    let t = s
      .replace(/[""«»„‟]/g, '"')
      .replace(/[''‚‛]/g, "'")
      .replace(/[•·∙◦]/g, '-')
      .replace(/[–—―]/g, '-')
      .replace(/&/g, '')
      .replace(/\s+/g, ' ')
      .trim();
    // Remove non-printable / unsupported glyphs
    t = t.normalize('NFKD').replace(/[^\u0009\u000A\u000D\u0020-\u007E]/g, '');
    return t;
  } catch {
    return s;
  }
};

export const downloadPdf = (content: NoteContent) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const MARGIN = 20;
  const TITLE = 24;
  const MODULE = 16;
  const CHAPTER = 14;
  const BODY = 11;
  const META = 10;
  const LINE = 6;

  let y = MARGIN;

  const addBreak = (needed: number) => {
    if (y + needed > pageHeight - MARGIN) {
      doc.addPage();
      y = MARGIN;
    }
  };

  // COVER PAGE
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');
  
  // Top border decoration
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 3, 'F');
  
  y = 60;
  
  // Course name centered
  doc.setFontSize(22);
  doc.setTextColor(0, 0, 0);
  doc.setFont(undefined, 'bold');
  doc.text(sanitizeText(content.subject.toUpperCase()), pageWidth / 2, y, { align: 'center' });
  
  y += 20;
  
  // Subtitle if course code exists
  if (content.courseCode) {
    doc.setFontSize(14);
    doc.setFont(undefined, 'normal');
    doc.text(`(${sanitizeText(content.courseCode)})`, pageWidth / 2, y, { align: 'center' });
    y += 15;
  }
  
  // Syllabus to Notes text
  y += 10;
  doc.setFontSize(16);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(37, 99, 235);
  doc.text('SYLLABUS TO NOTES', pageWidth / 2, y, { align: 'center' });
  
  // Footer on cover page
  y = pageHeight - 50;
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.setFont(undefined, 'bold');
  doc.text('SyllabusToNotes.com', pageWidth / 2, y, { align: 'center' });
  
  y += 10;
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('AI-Powered Comprehensive Study Notes', pageWidth / 2, y, { align: 'center' });
  
  y += 8;
  doc.text('www.syllabustonotes.com', pageWidth / 2, y, { align: 'center' });
  
  // Bottom border decoration
  doc.setFillColor(37, 99, 235);
  doc.rect(0, pageHeight - 3, pageWidth, 3, 'F');
  
  // TABLE OF CONTENTS PAGE
  if (content.modules && content.modules.length > 0) {
    doc.addPage();
    y = MARGIN + 10;
    
    doc.setFontSize(20);
    doc.setTextColor(0, 0, 0);
    doc.setFont(undefined, 'bold');
    doc.text('CONTENTS', pageWidth / 2, y, { align: 'center' });
    
    y += 20;
    
    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    
    content.modules.forEach((module, idx) => {
      if (y > pageHeight - 30) {
        doc.addPage();
        y = MARGIN;
      }
      
      doc.setFont(undefined, 'bold');
      doc.text(`${idx + 1}. ${sanitizeText(module.name)}`, MARGIN + 5, y);
      y += 8;
      
      module.chapters.forEach((chapter, chIdx) => {
        if (y > pageHeight - 25) {
          doc.addPage();
          y = MARGIN;
        }
        doc.setFont(undefined, 'normal');
        const chapterText = `   ${idx + 1}.${chIdx + 1} ${sanitizeText(chapter.name)}`;
        doc.text(chapterText, MARGIN + 10, y);
        y += 6;
      });
      
      y += 4;
    });
  }
  
  // Start content on new page
  doc.addPage();
  y = MARGIN;

  const drawModuleHeader = (label: string, description?: string) => {
    // Start module on new page
    doc.addPage();
    y = MARGIN;
    
    // Module header with dark background
    doc.setFillColor(0, 0, 0);
    doc.rect(MARGIN, y, pageWidth - 2 * MARGIN, 20, 'F');
    
    doc.setFontSize(MODULE);
    doc.setTextColor(255, 255, 255);
    doc.setFont(undefined, 'bold');
    doc.text(sanitizeText(label), MARGIN + 5, y + 12);
    y += 28;
    
    // Module description if available
    if (description) {
      doc.setFontSize(BODY);
      doc.setTextColor(60, 60, 60);
      doc.setFont(undefined, 'normal');
      const descLines = doc.splitTextToSize(sanitizeText(description), pageWidth - 2 * MARGIN - 10);
      doc.text(descLines, MARGIN + 5, y);
      y += descLines.length * LINE + 10;
    }
  };

  const drawChapterHeader = (label: string, important?: boolean) => {
    addBreak(15);
    
    doc.setFontSize(CHAPTER);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text(sanitizeText(label), MARGIN, y);
    
    if (important) {
      doc.setFontSize(9);
      doc.setTextColor(245, 158, 11);
      doc.text('★ IMPORTANT', pageWidth - MARGIN, y, { align: 'right' });
    }
    
    // Underline
    y += 2;
    doc.setDrawColor(0, 0, 0);
    doc.setLineWidth(0.5);
    doc.line(MARGIN, y, pageWidth - MARGIN, y);
    y += 10;
  };

  const writeLabel = (label: string, color: [number, number, number]) => {
    doc.setFont(undefined, 'bold');
    doc.setFontSize(13);
    doc.setTextColor(color[0], color[1], color[2]);
    doc.text(sanitizeText(label), MARGIN + 5, y);
    y += 7;
    doc.setFont(undefined, 'normal');
    doc.setFontSize(BODY);
  };

  const writeParagraph = (text: string, color: [number, number, number] = [55, 65, 81]) => {
    doc.setTextColor(color[0], color[1], color[2]);
    const clean = sanitizeText(text);
    const split = doc.splitTextToSize(clean, pageWidth - 2 * MARGIN - 10);
    addBreak(split.length * LINE + 6);
    doc.text(split, MARGIN + 5, y);
    y += split.length * LINE + 8;
  };

  const writeBullets = (items: string[], color: [number, number, number]) => {
    doc.setTextColor(color[0], color[1], color[2]);
    for (const item of items) {
      const clean = sanitizeText(item);
      const split = doc.splitTextToSize(`- ${clean}`, pageWidth - 2 * MARGIN - 15);
      addBreak(split.length * LINE + 4);
      doc.text(split, MARGIN + 10, y);
      y += split.length * LINE + 3;
    }
    y += 6;
  };

  if (content.modules) {
    content.modules.forEach((m, mi) => {
      drawModuleHeader(`Module ${mi + 1}: ${m.name}`, m.description);
      
      m.chapters.forEach((c, ci) => {
        drawChapterHeader(`${c.name}`, c.isImportant);

        if (c.definition) {
          writeLabel('Definition:', [126, 34, 206]);
          doc.setFont(undefined, 'italic');
          writeParagraph(c.definition, [75, 85, 99]);
          doc.setFont(undefined, 'normal');
        }

        writeLabel('Overview:', [75, 85, 99]);
        writeParagraph(c.description, [75, 85, 99]);

        writeLabel('📌 Key Points:', [37, 99, 235]);
        writeBullets(c.keyPoints || [], [55, 65, 81]);

        if (c.importantConcepts?.length) {
          writeLabel('🎯 Important Concepts:', [217, 119, 6]);
          writeBullets(c.importantConcepts, [146, 64, 14]);
        }

        if (c.formulas?.length) {
          writeLabel('🔢 Formulas:', [3, 105, 161]);
          doc.setFont('courier', 'normal');
          doc.setTextColor(12, 74, 110);
          for (const f of c.formulas) {
            const split = doc.splitTextToSize(f, pageWidth - 2 * MARGIN - 16);
            addBreak(split.length * LINE + 6);
            doc.setFillColor(240, 249, 255);
            doc.roundedRect(MARGIN + 8, y - 3, pageWidth - 2 * MARGIN - 16, split.length * LINE + 4, 1, 1, 'F');
            doc.text(split, MARGIN + 10, y);
            y += split.length * LINE + 6;
          }
          doc.setFont(undefined, 'normal');
        }

        writeLabel('💡 Practical Applications:', [30, 64, 175]);
        writeParagraph(c.applications, [30, 58, 138]);

        if (c.studyTips?.length) {
          writeLabel('✅ Study Tips:', [5, 150, 105]);
          writeBullets(c.studyTips, [6, 95, 70]);
        }

        y += 6;
      });
      y += 6;
    });
  } else if (content.topics) {
    addBreak(20);
    doc.setFontSize(MODULE);
    doc.setTextColor(124, 58, 237);
    doc.setFont(undefined, 'bold');
    doc.text('📚 Topics Covered:', MARGIN, y);
    y += 12;

    doc.setFontSize(BODY);
    doc.setFont(undefined, 'normal');
    for (let i = 0; i < content.topics.length; i++) {
      addBreak(20);
      doc.setFont(undefined, 'bold');
      doc.text(`${i + 1}. ${content.topics[i]}`, MARGIN, y);
      y += 7;
      doc.setFont(undefined, 'normal');
      const desc = getTopicDescription(content.topics[i]);
      const split = doc.splitTextToSize(desc, pageWidth - 2 * MARGIN);
      addBreak(split.length * LINE + 8);
      doc.text(split, MARGIN + 5, y);
      y += split.length * LINE + 6;

      const kps = getKeyPoints(content.topics[i]);
      doc.setFont(undefined, 'bold');
      doc.text('Key Points:', MARGIN + 5, y);
      y += 7;
      doc.setFont(undefined, 'normal');
      for (const kp of kps) {
        const s = doc.splitTextToSize(`- ${sanitizeText(kp)}`, pageWidth - 2 * MARGIN - 10);
        addBreak(s.length * LINE + 4);
        doc.text(s, MARGIN + 10, y);
        y += s.length * LINE + 3;
      }
      y += 8;
    }
  }

  // Footer note
  addBreak(28);
  doc.setFillColor(239, 246, 255);
  doc.roundedRect(MARGIN, y, pageWidth - 2 * MARGIN, 30, 3, 3, 'F');
  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y, pageWidth - MARGIN, y);
  doc.setFont(undefined, 'bold');
  doc.setFontSize(12);
  doc.setTextColor(37, 99, 235);
  doc.text('SyllabusToNotes.com', pageWidth / 2, y + 14, { align: 'center' });
  doc.setFont(undefined, 'normal');
  doc.setFontSize(10);
  doc.setTextColor(107, 114, 128);
  doc.text('AI-Powered Comprehensive Study Notes', pageWidth / 2, y + 22, { align: 'center' });

  // Page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  const safeSubject = sanitizeText(content.subject).replace(/[^a-z0-9]+/gi, '_').replace(/^_+|_+$/g, '');
  doc.save(`${safeSubject}_syllabus_to_notes.pdf`);
};
