import jsPDF from 'jspdf';

export interface Chapter {
  name: string;
  description: string;
  definition?: string;
  keyPoints: string[];
  applications: string;
  formulas?: string[];
  importantConcepts?: string[];
  commonMistakes?: string[];
  studyTips?: string[];
  relatedTopics?: string[];
  isImportant?: boolean;
}

export interface Module {
  name: string;
  description?: string;
  chapters: Chapter[];
}

export interface NoteContent {
  title: string;
  subject: string;
  courseCode?: string;
  topics?: string[];
  modules?: Module[];
  isPremium?: boolean;
}

export const generatePdfContent = (content: NoteContent): string => {
  const { title, subject, courseCode, topics, modules } = content;
  
  // Generate content based on whether we have AI-analyzed modules or simple topics
  const mainContent = modules ? generateModuleContent(modules) : generateTopicContent(topics || []);
  
  return `
    <div style="font-family: Arial, sans-serif; line-height: 1.8; position: relative;">
      <!-- Watermark -->
      <div style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg); 
                  font-size: 80px; color: rgba(37, 99, 235, 0.05); font-weight: bold; z-index: -1; 
                  white-space: nowrap; pointer-events: none;">
        SyllabusToNotes.com
      </div>
      
      <!-- Header -->
      <div style="background: linear-gradient(135deg, #2563eb 0%, #1e40af 100%); 
                  color: white; padding: 30px; border-radius: 12px; margin-bottom: 30px;">
        <h1 style="margin: 0 0 10px 0; font-size: 32px; border-bottom: 3px solid white; padding-bottom: 15px;">
          ${title}
        </h1>
        <div style="display: flex; gap: 20px; margin-top: 15px; font-size: 14px;">
          <p style="margin: 0;"><strong>Subject:</strong> ${subject}</p>
          ${courseCode ? `<p style="margin: 0;"><strong>Course Code:</strong> ${courseCode}</p>` : ''}
        </div>
      </div>
      
      ${mainContent}
      
      <!-- Study Tips Section -->
      <div style="margin-top: 50px; padding: 25px; background: linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%); 
                  border-radius: 12px; border-left: 5px solid #2563eb;">
        <h3 style="color: #2563eb; margin-top: 0; font-size: 20px; display: flex; align-items: center;">
          💡 Essential Study Tips
        </h3>
        <ul style="color: #1e40af; margin: 15px 0; line-height: 2;">
          <li><strong>Regular Review:</strong> Review these notes daily for better retention and understanding</li>
          <li><strong>Active Learning:</strong> Create your own examples and practice problems for each concept</li>
          <li><strong>Practice:</strong> Solve previous year questions and sample papers regularly</li>
          <li><strong>Study Groups:</strong> Form study groups to discuss and clarify difficult topics</li>
          <li><strong>Time Management:</strong> Allocate more time to topics marked as important</li>
          <li><strong>Connections:</strong> Try to connect different topics to build a comprehensive understanding</li>
        </ul>
      </div>
      
      <!-- Footer -->
      <div style="margin-top: 30px; padding: 20px; background: #f9fafb; border-radius: 8px; 
                  text-align: center; color: #6b7280; border-top: 3px solid #2563eb;">
        <p style="margin: 0; font-size: 16px;">
          Generated by <strong style="color: #2563eb; font-size: 18px;">SyllabusToNotes.com</strong>
        </p>
        <p style="margin: 8px 0 0 0; font-size: 13px; color: #9ca3af;">
          AI-Powered Comprehensive Study Notes | Visit us at www.syllabustonotes.com
        </p>
      </div>
    </div>
  `;
};

const getTopicDescription = (topic: string): string => {
  const descriptions: { [key: string]: string } = {
    'Arrays': 'A data structure that stores a collection of elements, each identified by an array index. Arrays provide efficient random access and are fundamental to many algorithms.',
    'Linked Lists': 'A linear data structure where elements are stored in nodes, with each node containing a reference to the next node. Useful for dynamic memory allocation.',
    'Trees': 'A hierarchical data structure with a root node and child nodes, forming a parent-child relationship. Used in file systems, databases, and more.',
    'Graphs': 'A collection of nodes connected by edges, used to represent networks, relationships, and pathways in various applications.',
    'Sorting Algorithms': 'Algorithms that arrange elements in a specific order (ascending/descending). Common examples include bubble sort, merge sort, and quick sort.',
    'Hydrocarbons': 'Organic compounds consisting entirely of hydrogen and carbon atoms. They form the basis of organic chemistry.',
    'Functional Groups': 'Specific groups of atoms within molecules that are responsible for characteristic chemical reactions.',
    'Reactions': 'Chemical processes where substances are transformed into different substances through breaking and forming chemical bonds.',
    'Mechanisms': 'Step-by-step descriptions of how chemical reactions occur at the molecular level.',
    'Balance Sheet': 'A financial statement that reports company assets, liabilities, and shareholders equity at a specific point in time.',
    'Income Statement': 'A financial statement showing revenues and expenses during a specific period, resulting in net profit or loss.',
    'Cash Flow': 'The total amount of money being transferred in and out of a business, affecting liquidity.',
    'Ratios': 'Financial metrics used to evaluate various aspects of company performance and financial health.',
    'Cardiovascular': 'The system comprising the heart and blood vessels responsible for circulating blood throughout the body.',
    'Respiratory': 'The biological system for gas exchange, bringing oxygen into the body and removing carbon dioxide.',
    'Nervous System': 'The network of nerve cells and fibers that transmits signals between different parts of the body.',
    'Muscular': 'The system of muscles that enables movement and maintains posture in the body.',
    'Ecosystems': 'A community of living organisms interacting with their physical environment.',
    'Pollution': 'The introduction of harmful substances or contaminants into the natural environment.',
    'Biodiversity': 'The variety of life in all its forms, levels, and combinations, including diversity of species.',
    'Climate Change': 'Long-term shifts in temperatures and weather patterns, primarily caused by human activities.',
    'SEO': 'Search Engine Optimization - techniques to improve website visibility in search engine results.',
    'Social Media': 'Digital platforms enabling users to create and share content, facilitating online social networking.',
    'Content Marketing': 'Strategic marketing approach focused on creating valuable content to attract and retain audiences.',
    'Analytics': 'The systematic analysis of data to gain insights and make informed decisions.',
  };
  
  return descriptions[topic] || `Comprehensive coverage of ${topic} including fundamental concepts, practical applications, and key theoretical foundations.`;
};

const generateModuleContent = (modules: Module[]): string => {
  return `
    <h2 style="color: #7c3aed; margin-top: 30px; font-size: 24px; border-bottom: 3px solid #7c3aed; padding-bottom: 10px;">
      📚 Course Content
    </h2>
    ${modules.map((module, moduleIndex) => `
      <div style="margin: 40px 0; page-break-inside: avoid;">
        <div style="background: linear-gradient(135deg, #7c3aed 0%, #6d28d9 100%); 
                    color: white; padding: 20px; border-radius: 10px; margin-bottom: 20px;">
          <h2 style="margin: 0; font-size: 22px;">
            Module ${moduleIndex + 1}: ${module.name}
          </h2>
          ${module.description ? `<p style="margin: 10px 0 0 0; opacity: 0.95; font-size: 14px;">${module.description}</p>` : ''}
        </div>
        
        ${module.chapters.map((chapter, chapterIndex) => `
          <div style="background: ${chapter.isImportant ? '#fef3c7' : '#f3f4f6'}; 
                      margin: 20px 0; padding: 25px; 
                      border-left: 5px solid ${chapter.isImportant ? '#f59e0b' : '#2563eb'}; 
                      border-radius: 8px; page-break-inside: avoid;">
            
            <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 15px;">
              <h3 style="color: #1f2937; margin: 0; font-size: 20px;">
                ${moduleIndex + 1}.${chapterIndex + 1} ${chapter.name}
              </h3>
              ${chapter.isImportant ? '<span style="background: #f59e0b; color: white; padding: 4px 12px; border-radius: 12px; font-size: 11px; font-weight: bold;">⭐ IMPORTANT</span>' : ''}
            </div>
            
            ${chapter.definition ? `
              <div style="background: white; padding: 15px; border-radius: 6px; margin: 15px 0; border-left: 3px solid #8b5cf6;">
                <strong style="color: #8b5cf6; font-size: 15px;">📖 Definition:</strong>
                <p style="color: #374151; margin: 8px 0 0 0; line-height: 1.8; font-style: italic;">
                  ${chapter.definition}
                </p>
              </div>
            ` : ''}
            
            <div style="background: white; padding: 15px; border-radius: 6px; margin: 15px 0;">
              <strong style="color: #4b5563; font-size: 15px;">📝 Overview:</strong>
              <p style="color: #4b5563; margin: 8px 0 0 0; line-height: 1.9;">
                ${chapter.description}
              </p>
            </div>
            
            <div style="background: white; padding: 18px; border-radius: 6px; margin: 15px 0;">
              <strong style="color: #2563eb; font-size: 16px; display: block; margin-bottom: 12px;">
                📌 Key Points to Remember:
              </strong>
              <ul style="margin: 0; padding-left: 25px; color: #374151; line-height: 2;">
                ${chapter.keyPoints.map(point => `
                  <li style="margin: 8px 0; padding-left: 5px;">${point}</li>
                `).join('')}
              </ul>
            </div>
            
            ${chapter.importantConcepts && chapter.importantConcepts.length > 0 ? `
              <div style="background: #fef3c7; padding: 18px; border-radius: 6px; margin: 15px 0; border-left: 3px solid #f59e0b;">
                <strong style="color: #d97706; font-size: 16px; display: block; margin-bottom: 12px;">
                  🎯 Important Concepts:
                </strong>
                <ul style="margin: 0; padding-left: 25px; color: #92400e; line-height: 2;">
                  ${chapter.importantConcepts.map(concept => `
                    <li style="margin: 8px 0;">${concept}</li>
                  `).join('')}
                </ul>
              </div>
            ` : ''}
            
            ${chapter.formulas && chapter.formulas.length > 0 ? `
              <div style="background: #f0f9ff; padding: 18px; border-radius: 6px; margin: 15px 0; border-left: 3px solid #0ea5e9;">
                <strong style="color: #0369a1; font-size: 16px; display: block; margin-bottom: 12px;">
                  🔢 Formulas & Equations:
                </strong>
                <div style="background: white; padding: 15px; border-radius: 4px;">
                  ${chapter.formulas.map(formula => `
                    <div style="margin: 10px 0; padding: 10px; background: #f8fafc; border-radius: 4px; font-family: 'Courier New', monospace; color: #0c4a6e;">
                      ${formula}
                    </div>
                  `).join('')}
                </div>
              </div>
            ` : ''}
            
            <div style="background: #eff6ff; padding: 18px; border-radius: 6px; margin: 15px 0; border-left: 3px solid #3b82f6;">
              <strong style="color: #1e40af; font-size: 16px; display: block; margin-bottom: 10px;">
                💡 Practical Applications:
              </strong>
              <p style="color: #1e3a8a; margin: 0; line-height: 1.9;">
                ${chapter.applications}
              </p>
            </div>
            
            ${chapter.studyTips && chapter.studyTips.length > 0 ? `
              <div style="background: #f0fdf4; padding: 18px; border-radius: 6px; margin: 15px 0; border-left: 3px solid #10b981;">
                <strong style="color: #059669; font-size: 16px; display: block; margin-bottom: 12px;">
                  ✅ Study Tips:
                </strong>
                <ul style="margin: 0; padding-left: 25px; color: #065f46; line-height: 2;">
                  ${chapter.studyTips.map(tip => `
                    <li style="margin: 8px 0;">${tip}</li>
                  `).join('')}
                </ul>
              </div>
            ` : ''}
            
            ${chapter.commonMistakes && chapter.commonMistakes.length > 0 ? `
              <div style="background: #fef2f2; padding: 18px; border-radius: 6px; margin: 15px 0; border-left: 3px solid #ef4444;">
                <strong style="color: #dc2626; font-size: 16px; display: block; margin-bottom: 12px;">
                  ⚠️ Common Mistakes to Avoid:
                </strong>
                <ul style="margin: 0; padding-left: 25px; color: #991b1b; line-height: 2;">
                  ${chapter.commonMistakes.map(mistake => `
                    <li style="margin: 8px 0;">${mistake}</li>
                  `).join('')}
                </ul>
              </div>
            ` : ''}
            
            ${chapter.relatedTopics && chapter.relatedTopics.length > 0 ? `
              <div style="background: #faf5ff; padding: 15px; border-radius: 6px; margin: 15px 0; border-left: 3px solid #a855f7;">
                <strong style="color: #7e22ce; font-size: 15px;">
                  🔗 Related Topics:
                </strong>
                <p style="color: #6b21a8; margin: 8px 0 0 0;">
                  ${chapter.relatedTopics.join(' • ')}
                </p>
              </div>
            ` : ''}
            
          </div>
        `).join('')}
      </div>
    `).join('')}
  `;
};

const generateTopicContent = (topics: string[]): string => {
  return `
    <h2 style="color: #7c3aed; margin-top: 30px;">Topics Covered:</h2>
    <ul style="list-style-type: none; padding-left: 0;">
      ${topics.map(topic => `
        <li style="background: #f3f4f6; margin: 10px 0; padding: 15px; border-left: 4px solid #2563eb; border-radius: 4px;">
          <h3 style="color: #1f2937; margin: 0 0 10px 0;">${topic}</h3>
          <p style="color: #4b5563; margin: 0;">
            ${getTopicDescription(topic)}
          </p>
          <div style="margin-top: 10px; padding: 10px; background: white; border-radius: 4px;">
            <strong style="color: #2563eb;">Key Points:</strong>
            <ul style="margin: 5px 0; padding-left: 20px;">
              ${getKeyPoints(topic).map(point => `<li style="color: #374151;">${point}</li>`).join('')}
            </ul>
          </div>
        </li>
      `).join('')}
    </ul>
  `;
};

const getKeyPoints = (topic: string): string[] => {
  const keyPoints: { [key: string]: string[] } = {
    'Arrays': [
      'Fixed size, contiguous memory allocation',
      'O(1) access time using index',
      'Common operations: insert, delete, search, traverse',
      'Types: 1D, 2D, multi-dimensional arrays'
    ],
    'Linked Lists': [
      'Dynamic size, non-contiguous memory',
      'Types: Singly, Doubly, Circular',
      'Efficient insertion and deletion',
      'Sequential access O(n)'
    ],
    'Trees': [
      'Root, parent, child, leaf nodes',
      'Binary trees, BST, AVL, B-trees',
      'Traversal: Inorder, Preorder, Postorder',
      'Applications: file systems, decision trees'
    ],
    'Graphs': [
      'Vertices (nodes) and Edges',
      'Directed vs Undirected graphs',
      'Weighted vs Unweighted',
      'Traversal: BFS, DFS'
    ],
  };
  
  return keyPoints[topic] || [
    'Core concepts and definitions',
    'Practical applications and examples',
    'Common problems and solutions',
    'Best practices and techniques'
  ];
};

export const downloadPdf = (content: NoteContent) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = 20;
  
  // Function to add watermark on each page
  const addWatermark = () => {
    doc.setFontSize(50);
    doc.setTextColor(37, 99, 235, 0.05); // Very light blue with low opacity
    doc.text('SyllabusToNotes.com', pageWidth / 2, pageHeight / 2, {
      align: 'center',
      angle: 45,
    });
  };
  
  addWatermark();
  
  // Header with gradient effect (simulated)
  doc.setFillColor(37, 99, 235);
  doc.roundedRect(margin, yPosition, pageWidth - 2 * margin, 35, 3, 3, 'F');
  
  doc.setFontSize(24);
  doc.setTextColor(255, 255, 255);
  doc.text(content.title, pageWidth / 2, yPosition + 15, { align: 'center' });
  
  doc.setFontSize(11);
  doc.text(`Subject: ${content.subject}`, margin + 5, yPosition + 28);
  if (content.courseCode) {
    doc.text(`Course: ${content.courseCode}`, pageWidth - margin - 5, yPosition + 28, { align: 'right' });
  }
  
  yPosition += 45;
  
  // Generate content based on structure
  if (content.modules) {
    // AI-analyzed content with modules
    content.modules.forEach((module, moduleIndex) => {
      if (yPosition > 250) {
        doc.addPage();
        addWatermark();
        yPosition = 20;
      }
      
      // Module heading with background
      doc.setFillColor(124, 58, 237);
      doc.roundedRect(margin, yPosition - 5, pageWidth - 2 * margin, 15, 2, 2, 'F');
      
      doc.setFontSize(16);
      doc.setTextColor(255, 255, 255);
      doc.text(`Module ${moduleIndex + 1}: ${module.name}`, margin + 5, yPosition + 5);
      yPosition += 20;
      
      module.chapters.forEach((chapter, chapterIndex) => {
        if (yPosition > 260) {
          doc.addPage();
          addWatermark();
          yPosition = 20;
        }
        
        // Chapter heading with highlight for important topics
        const bgColor = chapter.isImportant ? [254, 243, 199] : [243, 244, 246];
        doc.setFillColor(bgColor[0], bgColor[1], bgColor[2]);
        doc.roundedRect(margin, yPosition - 2, pageWidth - 2 * margin, 12, 1, 1, 'F');
        
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.setFont(undefined, 'bold');
        const chapterTitle = `${moduleIndex + 1}.${chapterIndex + 1} ${chapter.name}`;
        doc.text(chapterTitle, margin + 5, yPosition + 6);
        
        if (chapter.isImportant) {
          doc.setFontSize(10);
          doc.setTextColor(245, 158, 11);
          doc.text('★ IMPORTANT', pageWidth - margin - 5, yPosition + 6, { align: 'right' });
        }
        
        yPosition += 15;
        
        // Definition (if available)
        if (chapter.definition) {
          if (yPosition > 250) {
            doc.addPage();
            addWatermark();
            yPosition = 20;
          }
          doc.setFillColor(243, 232, 255);
          doc.roundedRect(margin + 5, yPosition, pageWidth - 2 * margin - 10, 0, 1, 1, 'F');
          doc.setFont(undefined, 'bold');
          doc.setFontSize(11);
          doc.setTextColor(126, 34, 206);
          doc.text('Definition:', margin + 8, yPosition + 5);
          yPosition += 8;
          
          doc.setFont(undefined, 'italic');
          doc.setFontSize(10);
          doc.setTextColor(75, 85, 99);
          const splitDef = doc.splitTextToSize(chapter.definition, pageWidth - 2 * margin - 20);
          const defHeight = splitDef.length * 5 + 10;
          doc.setFillColor(243, 232, 255);
          doc.roundedRect(margin + 5, yPosition - 5, pageWidth - 2 * margin - 10, defHeight, 1, 1, 'F');
          doc.text(splitDef, margin + 8, yPosition);
          yPosition += splitDef.length * 5 + 12;
        }
        
        // Description
        if (yPosition > 250) {
          doc.addPage();
          addWatermark();
          yPosition = 20;
        }
        doc.setFont(undefined, 'bold');
        doc.setFontSize(11);
        doc.setTextColor(75, 85, 99);
        doc.text('Overview:', margin + 5, yPosition);
        yPosition += 6;
        
        doc.setFont(undefined, 'normal');
        doc.setFontSize(10);
        const splitDesc = doc.splitTextToSize(chapter.description, pageWidth - 2 * margin - 10);
        doc.text(splitDesc, margin + 5, yPosition);
        yPosition += splitDesc.length * 5 + 10;
        
        // Key Points
        if (yPosition > 240) {
          doc.addPage();
          addWatermark();
          yPosition = 20;
        }
        doc.setFont(undefined, 'bold');
        doc.setFontSize(11);
        doc.setTextColor(37, 99, 235);
        doc.text('📌 Key Points:', margin + 5, yPosition);
        yPosition += 7;
        
        doc.setFont(undefined, 'normal');
        doc.setFontSize(10);
        doc.setTextColor(55, 65, 81);
        chapter.keyPoints.forEach(point => {
          if (yPosition > 270) {
            doc.addPage();
            addWatermark();
            yPosition = 20;
          }
          const splitPoint = doc.splitTextToSize(`• ${point}`, pageWidth - 2 * margin - 15);
          doc.text(splitPoint, margin + 10, yPosition);
          yPosition += splitPoint.length * 5 + 3;
        });
        
        yPosition += 8;
        
        // Important Concepts (if available)
        if (chapter.importantConcepts && chapter.importantConcepts.length > 0) {
          if (yPosition > 240) {
            doc.addPage();
            addWatermark();
            yPosition = 20;
          }
          doc.setFont(undefined, 'bold');
          doc.setFontSize(11);
          doc.setTextColor(217, 119, 6);
          doc.text('🎯 Important Concepts:', margin + 5, yPosition);
          yPosition += 7;
          
          doc.setFont(undefined, 'normal');
          doc.setFontSize(10);
          doc.setTextColor(146, 64, 14);
          chapter.importantConcepts.forEach(concept => {
            if (yPosition > 270) {
              doc.addPage();
              addWatermark();
              yPosition = 20;
            }
            const splitConcept = doc.splitTextToSize(`• ${concept}`, pageWidth - 2 * margin - 15);
            doc.text(splitConcept, margin + 10, yPosition);
            yPosition += splitConcept.length * 5 + 3;
          });
          yPosition += 8;
        }
        
        // Formulas (if available)
        if (chapter.formulas && chapter.formulas.length > 0) {
          if (yPosition > 240) {
            doc.addPage();
            addWatermark();
            yPosition = 20;
          }
          doc.setFont(undefined, 'bold');
          doc.setFontSize(11);
          doc.setTextColor(3, 105, 161);
          doc.text('🔢 Formulas:', margin + 5, yPosition);
          yPosition += 7;
          
          doc.setFont('courier', 'normal');
          doc.setFontSize(10);
          doc.setTextColor(12, 74, 110);
          chapter.formulas.forEach(formula => {
            if (yPosition > 270) {
              doc.addPage();
              addWatermark();
              yPosition = 20;
            }
            doc.setFillColor(240, 249, 255);
            const formulaHeight = 8;
            doc.roundedRect(margin + 8, yPosition - 3, pageWidth - 2 * margin - 16, formulaHeight, 1, 1, 'F');
            doc.text(formula, margin + 10, yPosition + 2);
            yPosition += formulaHeight + 3;
          });
          doc.setFont(undefined, 'normal');
          yPosition += 8;
        }
        
        // Applications
        if (yPosition > 240) {
          doc.addPage();
          addWatermark();
          yPosition = 20;
        }
        doc.setFont(undefined, 'bold');
        doc.setFontSize(11);
        doc.setTextColor(30, 64, 175);
        doc.text('💡 Practical Applications:', margin + 5, yPosition);
        yPosition += 7;
        
        doc.setFont(undefined, 'normal');
        doc.setFontSize(10);
        doc.setTextColor(30, 58, 138);
        const splitApp = doc.splitTextToSize(chapter.applications, pageWidth - 2 * margin - 10);
        doc.text(splitApp, margin + 5, yPosition);
        yPosition += splitApp.length * 5 + 10;
        
        // Study Tips (if available)
        if (chapter.studyTips && chapter.studyTips.length > 0) {
          if (yPosition > 240) {
            doc.addPage();
            addWatermark();
            yPosition = 20;
          }
          doc.setFont(undefined, 'bold');
          doc.setFontSize(11);
          doc.setTextColor(5, 150, 105);
          doc.text('✅ Study Tips:', margin + 5, yPosition);
          yPosition += 7;
          
          doc.setFont(undefined, 'normal');
          doc.setFontSize(10);
          doc.setTextColor(6, 95, 70);
          chapter.studyTips.forEach(tip => {
            if (yPosition > 270) {
              doc.addPage();
              addWatermark();
              yPosition = 20;
            }
            const splitTip = doc.splitTextToSize(`• ${tip}`, pageWidth - 2 * margin - 15);
            doc.text(splitTip, margin + 10, yPosition);
            yPosition += splitTip.length * 5 + 3;
          });
          yPosition += 8;
        }
        
        // Common Mistakes (if available)
        if (chapter.commonMistakes && chapter.commonMistakes.length > 0) {
          if (yPosition > 240) {
            doc.addPage();
            addWatermark();
            yPosition = 20;
          }
          doc.setFont(undefined, 'bold');
          doc.setFontSize(11);
          doc.setTextColor(220, 38, 38);
          doc.text('⚠️ Common Mistakes:', margin + 5, yPosition);
          yPosition += 7;
          
          doc.setFont(undefined, 'normal');
          doc.setFontSize(10);
          doc.setTextColor(153, 27, 27);
          chapter.commonMistakes.forEach(mistake => {
            if (yPosition > 270) {
              doc.addPage();
              addWatermark();
              yPosition = 20;
            }
            const splitMistake = doc.splitTextToSize(`• ${mistake}`, pageWidth - 2 * margin - 15);
            doc.text(splitMistake, margin + 10, yPosition);
            yPosition += splitMistake.length * 5 + 3;
          });
          yPosition += 8;
        }
        
        yPosition += 12;
      });
      
      yPosition += 8;
    });
  } else if (content.topics) {
    // Simple topic-based content
    if (yPosition > 250) {
      doc.addPage();
      addWatermark();
      yPosition = 20;
    }
    doc.setFontSize(16);
    doc.setTextColor(124, 58, 237);
    doc.text('📚 Topics Covered:', margin, yPosition);
    yPosition += 12;
    
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    content.topics.forEach((topic, index) => {
      if (yPosition > 260) {
        doc.addPage();
        addWatermark();
        yPosition = 20;
      }
      
      doc.setFont(undefined, 'bold');
      doc.text(`${index + 1}. ${topic}`, margin, yPosition);
      yPosition += 7;
      
      doc.setFont(undefined, 'normal');
      const description = getTopicDescription(topic);
      const splitDescription = doc.splitTextToSize(description, pageWidth - 2 * margin);
      doc.text(splitDescription, margin + 5, yPosition);
      yPosition += splitDescription.length * 5 + 5;
      
      const keyPoints = getKeyPoints(topic);
      doc.setFont(undefined, 'bold');
      doc.text('Key Points:', margin + 5, yPosition);
      yPosition += 6;
      
      doc.setFont(undefined, 'normal');
      keyPoints.forEach(point => {
        if (yPosition > 270) {
          doc.addPage();
          addWatermark();
          yPosition = 20;
        }
        const splitPoint = doc.splitTextToSize(`• ${point}`, pageWidth - 2 * margin - 10);
        doc.text(splitPoint, margin + 10, yPosition);
        yPosition += splitPoint.length * 5 + 2;
      });
      
      yPosition += 10;
    });
  }
  
  // Footer
  if (yPosition > 235) {
    doc.addPage();
    addWatermark();
    yPosition = 20;
  }
  
  doc.setFillColor(239, 246, 255);
  doc.roundedRect(margin, yPosition, pageWidth - 2 * margin, 35, 3, 3, 'F');
  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.5);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  
  doc.setFontSize(12);
  doc.setTextColor(37, 99, 235);
  doc.setFont(undefined, 'bold');
  doc.text('SyllabusToNotes.com', pageWidth / 2, yPosition + 15, { align: 'center' });
  
  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(107, 114, 128);
  doc.text('AI-Powered Comprehensive Study Notes', pageWidth / 2, yPosition + 23, { align: 'center' });
  doc.text('Visit us at www.syllabustonotes.com', pageWidth / 2, yPosition + 29, { align: 'center' });
  
  // Save
  doc.save(`${content.title.replace(/[^a-z0-9]/gi, '_')}.pdf`);
};
